# fly.toml app configuration file generated for wxshackathon on 2025-06-24T20:06:06+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wxshackathon'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
