import "@/styles/globals.css";
import type { Metadata } from "next";

import Navbar from "@/components/navigation/navbar/Navbar";
import Footer from "@/components/navigation/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <head>
        {/* Tbh idk how to get Adobe Fonts to work in app-router, so this is a janky <head> workaround */}
        <link rel="stylesheet" href="https://use.typekit.net/inx8qlb.css"/>
      </head>
      <body className={`antialiased bg-background text-foreground global-font-stack tracking-[-0.01em]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
